### ISSUE TITLE
2주차 리뷰입니다 😊

### ISSUE THREAD

**Issue by sonypark** [pbg0205/codesquad-cocoa-java#1]
안녕하세요 cooper, 소니입니다. 미션 잘 구현하셨네요! 역할별로 클래스 분리를 하시려고 노력한 모습이 보입니다👍 
몇가지 아쉬운 점이 남아 간단한 피드백 드렸으니 참고 부탁드려요 💪

1. Member 클래스
        - isPasswordType 메서드에서 if문 사용하지 않고 바로 리턴하는건 어떨까요?

```java
public boolean isPasswordType() {
        if (REGULAR_EXPRESSION_OF_PASSWORD.matcher(this.password).find()) {
            return true;
        }
        return false;
    }
```
```java
public boolean isPasswordType() {
        return REGULAR_EXPRESSION_OF_PASSWORD.matcher(this.password).find();
    }
```

2. 자바에서 메서드의 이름은 동사로 적고, 맨 첫번째 문자는 소문자로 적는 스타일을 따릅니다.
            - [https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names](https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names)
            - AllValidation 메서드명을 수정해볼까요?
            - 이 부분말고도 메서드명 수정이 필요한 곳이 보이네요. 다른 곳도 수정해주세요~
3. id가 null인지 체크하는 로직은 생성자에서 id를 받을 때 해주면 어떨까요?
            - id가 null일 경우는 Member 객체가 생성되지 않도록 하는게 더 안전한 방법일 것 같아요.
4. Member 클래스와 UseDate 클래스에서 equlas와 hashcode를 오버라이딩 해주었는데, 그 이유는 무엇인가요? equals와 hashcode를 꼭 같이 오버라이딩 해줘야할까요? 그래야한다면 이유가 무엇일까요? 이 부분에 대해 학습해보시면 좋을 것 같아요!
5. MemberList와 같이 사용하지 않는 클래스는 삭제해주세요
6. 조건문이 긴 경우 메서드로 분리하면 가독성이 더 좋아집니다.

```java
if (payType.equals("현금") || payType.equalsIgnoreCase("cash")) {
    return "cash";
}

if (payType.equals("카드") || payType.equalsIgnoreCase("card")) {
    return "card";
}
```

**Comment by pbg0205** [comment]
리뷰해신 부분 우선적으로 코드 수정 완료했습니다.
항상 부족한 부분에 대해 고민이 많았는데 먼저 코드 리뷰 해주셔서 감사합니다!
혹시나 부족한 부분 있으면 아낌없이 조언 부탁드립니다😊
